# Generated by Django 2.2 on 2022-05-31 00:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220529_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('submit_time', models.DateTimeField(default=datetime.datetime(2022, 5, 31, 7, 41, 32, 142255))),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Problem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Student')),
            ],
        ),
    ]
