# Generated by Django 2.2 on 2022-06-01 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20220601_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 15, 17, 11, 254877)),
        ),
    ]
