# Generated by Django 2.2 on 2022-06-01 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20220601_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='problem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 16, 16, 44, 845483)),
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
