# Generated by Django 2.2 on 2022-06-01 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20220601_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 16, 58, 31, 301393)),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10),
        ),
    ]
