# Generated by Django 2.2 on 2022-06-01 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20220601_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 20, 45, 26, 421799)),
        ),
        migrations.AlterField(
            model_name='problem',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 20, 45, 26, 421799)),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.IntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D')], default=0),
        ),
    ]
