# Generated by Django 2.2 on 2022-06-04 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20220604_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 15, 46, 56, 140041)),
        ),
        migrations.AlterField(
            model_name='problem',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 15, 46, 56, 140041)),
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(default='no name', max_length=255),
        ),
    ]
